GET http://localhost:8080/persons/by-name-and-surname?name=Odin&surname=Odin

###
GET http://localhost:8080/persons/by-city?city=SPb

###
GET http://localhost:8080/persons/by-age?age=10

###
GET http://localhost:8080/persons